[package]
name = "ttygrid"
version = "0.1.0"
authors = ["Erik Hollensbe <linux@hollensbe.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = ">=0"

[dev-dependencies]
rand = "*"
